CREATE DATABASE	CursoDeFerias

USE CursoDeFerias

CREATE TABLE ENDERECOS(
	COD_ENDERECO INT PRIMARY KEY IDENTITY(1,1),
	CEP INT NOT NULL,
	LOGRADOURO VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	UF CHAR(2) NOT NULL
)

CREATE TABLE CLIENTES(
	COD_CLIENTE INT PRIMARY KEY IDENTITY(1,1),
	COD_ENDERECO INT FOREIGN KEY REFERENCES ENDERECOS(COD_ENDERECO) NOT NULL,
	CPF VARCHAR(14) NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	TELEFONE VARCHAR(15),
	EMAIL VARCHAR(50),
	NUMERO SMALLINT NOT NULL,
	COMPLEMENTO VARCHAR(30)
)

CREATE TABLE VENDAS(
	COD_VENDA INT PRIMARY KEY IDENTITY(1,1),
	COD_CLIENTE INT FOREIGN KEY REFERENCES CLIENTES(COD_CLIENTE),
	DATA_VENDA DATETIME NOT NULL,
	SUBTOTAL DECIMAL(10,2) NOT NULL,
	DESCONTO DECIMAL(10,2),
	TOTAL DECIMAL(10,2) NOT NULL,
	ENTREGA CHAR(1)
)


CREATE TABLE VENDAS_ITENS(
	COD_VENDA INT FOREIGN KEY REFERENCES VENDAS(COD_VENDA) ,
	COD_PRODUTO INT FOREIGN KEY REFERENCES PRODUTOS(COD_PRODUTO),
	QUANTIDADE SMALLINT NOT NULL,
	CONSTRAINT PK_VENDAS_ITENS PRIMARY KEY(COD_VENDA, COD_PRODUTO)
)


CREATE TABLE ENDERECO_ENTREGA(
	COD_ENDERECO INT FOREIGN KEY REFERENCES ENDERECOS(COD_ENDERECO),
	COD_VENDA INT FOREIGN KEY REFERENCES VENDAS(COD_VENDA),
	NUMERO SMALLINT NOT NULL,
	COMPLEMENTO VARCHAR(30),
	CONSTRAINT PK_ENDERECOS_ENTREGA PRIMARY KEY(COD_ENDERECO, COD_VENDA)
)

CREATE TABLE Teste(
	CodTeste INT PRIMARY KEY IDENTITY(1,1),
	NomeTeste VARCHAR(50),
	DataTeste DATETIME,
	CustoTeste DECIMAL(12,2)
)
